# Site configuration

url: "https://rtsofware.github.io/"
baseurl: "/"
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown

kramdown:
  auto_ids: false

# Content configuration

title: Real Time Software
description: Corporate webpage for RTSoftware
# keywords:
source_link: https://github.com/RTSofware/rtsofware.github.io
favicon: img/favicon.ico
touch_icon: img/apple-touch-icon.png
